# Run scripts/links.sh to setup these symlinks

$(pwd)/zsh/work.zsh:$HOME/.config/zsh/work.zsh
$(pwd)/zsh/.zprofile_work:$HOME/.config/zsh/.zprofile
$(pwd)/git/global-config/work.gitconfig:$HOME/.gitconfig

