# Run scripts/links.sh to setup these symlinks

$(pwd)/zsh/work.zsh:$HOME/.config/zsh/work.zsh
$(pwd)/git/global-config/work.gitconfig:$HOME/.gitconfig
$(pwd)/git/global-config/personal.gitconfig:$HOME/.gitconfig_personal
