# Run scripts/links.sh to setup these hardlinks

# Define an array of symbolic link sources and targets
$(pwd)/zsh/work.zsh:$HOME/.config/zsh/work.zsh
$(pwd)/zsh/.zprofile_work:$HOME/.config/zsh/.zprofile

