# Work-specific files managed by third-party apps that overwrite symlinks.
# Run ./scripts/sync.sh pull sync_config_work.conf to copy from system -> repo
# Run ./scripts/sync.sh push sync_config_work.conf to copy from repo -> system
#
# Format: $(pwd)/repo/path:$HOME/system/path

$(pwd)/arc/StorableSidebar.json:$HOME/Library/Application\ Support/Arc/StorableSidebar.json
