# Files/directories managed by third-party apps that overwrite symlinks.
# Run ./scripts/sync.sh pull to copy from system -> repo
# Run ./scripts/sync.sh push to copy from repo -> system
#
# Format: $(pwd)/repo/path:$HOME/system/path
$(pwd)/htop/htoprc:$HOME/.config/htop/htoprc
