# git:
#   paging:
#     colorArg: always
#     pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}
# gui:
#   showIcons: true

gui:
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --commit-style box
